services:
  node:
    image: node:14
    ports:
      - "4000:4000"
    volumes:
      - ./:/code
    links:
      - postgresql
      - redis
    command: sh -c "cd /code && npm install && npm run dev"
  postgresql:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresvolume:/var/lib/postgresql/data
      - ./entrypoint_db.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      - POSTGRES_PASSWORD=root
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  postgresvolume: {}